Fixed several wallet crashes due to wrong use of getColor() function:
W/CrashReporter: [main] crashing because of uncaught exception
    java.lang.NoSuchMethodError: No virtual method getColor(I)I in class Lgalilel/org/galilelwallet/ui/base/BaseDrawerActivity; or its super classes (declaration of
        at galilel.org.galilelwallet.ui.base.BaseDrawerActivity.updateBlockchainState(BaseDrawerActivity.java:243) ~[na:0.0]
        at galilel.org.galilelwallet.ui.base.BaseDrawerActivity.onResume(BaseDrawerActivity.java:138) ~[na:0.0]
        at galilel.org.galilelwallet.ui.wallet_activity.WalletActivity.onResume(WalletActivity.java:153) ~[na:0.0]
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1241) ~[na:0.0]
        at android.app.Activity.performResume(Activity.java:6063) ~[na:0.0]
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2945) ~[na:0.0]
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2987) ~[na:0.0]
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2370) ~[na:0.0]
        at android.app.ActivityThread.access$800(ActivityThread.java:148) ~[na:0.0]
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283) ~[na:0.0]
        at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
        at android.os.Looper.loop(Looper.java:135) ~[na:0.0]
        at android.app.ActivityThread.main(ActivityThread.java:5272) ~[na:0.0]
        at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
        at java.lang.reflect.Method.invoke(Method.java:372) ~[na:0.0]
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909) ~[na:0.0]
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704) ~[na:0.0]
E/GalilelApplication: [main] crash occured..